# Generated by Django 3.2 on 2021-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='default_user_pic.png', upload_to='profile_pics/'),
        ),
    ]
